### ISSUE TITLE
Loading model gives error.

### ISSUE THREAD

**Issue by amiralia** [taolei87/text_convnet#2]
Generally whenever I try to load a model, either pre-saved or freshly computed, it throws an error back at me. Here's the trace:

"File "main.py", line 415, in main
    model.load_model(args.load)
  File "main.py", line 204, in load_model
    param_values, args, nclasses = pickle.load(fin)
ValueError: too many values to unpack"

**Comment by amiralia** [comment]
In my local version, changing line 204 to the following fixed the problem:
            return_obj = pickle.load(fin)
            param_values = return_obj[0]
            args = return_obj[1]
            nclasses = return_obj[2]

**Comment by taolei87** [comment]
Hi @amiralia 

Thank you! I've modified the code.
